version: '3.7'
services:
  db-analytics:
    image: postgres:11.1
    environment:
    - POSTGRES_USER=analytics
    - POSTGRES_PASSWORD=passwordanalytics
    ports:
    - 15432:5432
    expose:
    - 5432
    volumes:
    - db-analytics-data:/var/lib/postgresql/data/
    networks:
    - backend

  pgslowpoke:
    depends_on:
    - db-analytics
    build:
      context: ./
      dockerfile: Dockerfile
    image: multicon/pgslowpoke
    ports:
    - 8080:8080
    - 5005:5005
    expose:
    - 8080
    - 5005
    networks:
    - backend
    environment:
    - SPRING_PROFILES_ACTIVE=prod
    - SERVER_PORT=8080
    - SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://db-analytics:5432/analytics
    - SPRING_DATASOURCE_USERNAME=analytics
    - SPRING_DATASOURCE_PASSWORD=passwordanalytics
    - JAVA_OPTS=-Xmx500m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005



networks:
  backend:
    driver: bridge

volumes:
  db-analytics-data:
