version: '3.7'
services:
  db-analytics:
    image: postgres:11.1
    environment:
    - POSTGRES_USER=analytics
    - POSTGRES_PASSWORD=passwordanalytics
    ports:
    - 15432:5432
    expose:
    - 5432
    volumes:
    - db-analytics-data:/var/lib/postgresql/data/
    networks:
    - backend

  db-target:
    image: postgres:11.1
    environment:
    - POSTGRES_USER=target
    - POSTGRES_PASSWORD=passwordtarget
    ports:
    - 15433:5432
    expose:
    - 5432
    volumes:
    - db-target-data:/var/lib/postgresql/data/
    networks:
    - backend


networks:
  backend:
    driver: bridge

volumes:
  db-analytics-data:
  db-target-data: