logging:
  path: logs
  file: logs/pgslowpoke.log
  level:
    org.springframework.web: DEBUG
    ru.multicon: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://db-analytics:5432/analytics
    username: analytics
    password: passwordanalytics
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true
    contexts: prod, test

server:
  tomcat:
    max-threads: 5
  port: 8080



