logging:
  path: logs
  file: logs/pgslowpoke.log
  level:
    org.springframework.web: DEBUG
    ru.multicon: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://ec2-50-17-250-38.compute-1.amazonaws.com:5432/d5cspb8gct3jmk
    username: udkainskasufko
    password: ${HEROKU_DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: false
    contexts: prod, test

server:
  tomcat:
    max-threads: 5
  port: 8080



